default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: df0b7gsi64pmd2
  pool: 5
  username: muuxlwountjmwr
  password: ktAsDwEcSiGsOumj0N8K2GhrFI
  host: ec2-54-83-61-45.compute-1.amazonaws.com
