default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: dcnktu38j0mpo7
  pool: 5
  username: cclravmxfrxdwo
  password: K3epbG0euIBzjRPmcNzfw4Pn7I
  host: ec2-54-225-165-132.compute-1.amazonaws.com
